In [20]:
import pandas as pd
import numpy as np
import pandas_datareader as pdr
import os
import requests

In [21]:
# 0050 Y110Q3
TW0050 ={
    'name':'tech',
    'portfolio':[
        "1101", "1216", "1301", "1303", "1326", "1402", "1590", "2002", "2207", "2303", 
        "2308", "2317", "2324", "2327", "2330", "2357", "2379", "2382", "2395", #"2311",
        "2408", "2409", "2412", "2603", "2609", "2615", "2801", "2880", "2881", "2882", 
        "2884", "2885", "2886", "2887", "2891", "2892", "2912", "3008", "3034", "3045", 
        "4904", "4938", "5880", "6415", "6505", "8046", "8454", "9910"
    ] 
}
    
# Tech     
Tech ={
    'name':'tech',
    'portfolio':[
        '2317', # 鴻海
        '2409', # 友達
        '2330', # 台積電
        '2303', # 聯電
        '2301', # 光寶科
        '2308', # 台達電
        '2356', # 英業達
        # '2353', # 宏碁
        # '2312', # 金寶
        # '2324', # 仁寶
        # '6770', # 力積電
        # '2313', # 華通
        # '2327', # 國巨
        # '3481', # 群創
    ]
}

# Financial
Financial ={
    'name':'financial',
    'portfolio':[
        '2891', # 中信金
        '2883', # 開發金
        '2885', # 元大金
        '2882', # 國泰金
        '2881', # 富邦金
        '2892', # 第一金
        '5880', # 合庫金
        '2884', # 玉山金
        # '2887', # 台新金
        # '2801', # 彰銀
        # '2890', # 永豐金
        # '2886', # 兆豐金
        # '2888', # 新光金
    ]
}


# experiments
Portfolio = Financial

# stock = '2330'
stock_period = ('2018/01/01', '2021/12/31')

In [22]:
stock_df=[]
for stock in Portfolio['portfolio']: 
    print(f'Start Download {stock}')
    df = pdr.DataReader(str(stock)+'.TW', 'yahoo', start=stock_period[0], end=stock_period[1])
    df[stock] = df['Close']
    df['date'] = df.index
    stock_df.append(df[['date',stock]])
    
df = pd.concat(stock_df,axis=1).drop(columns='date')
df.index = df.index.to_series().apply(lambda x : str(x).replace('-','')[:8])
df.index.name = 'DateTime'
name = Portfolio['name']
df.to_csv(os.path.join('data',f'{name}.csv'))
df

Start Download 2891
Start Download 2883
Start Download 2885
Start Download 2882
Start Download 2881
Start Download 2892
Start Download 5880
Start Download 2884

,2891,2883,2885,2882,2881,2892,5880,2884
DateTime,,,,,,,,
20180102,20.450001,10.10,13.269230,53.953381,46.363636,18.422365,14.938341,14.512654
20180103,20.650000,10.10,13.413461,54.948830,46.818180,18.422365,15.028061,14.858193
20180104,20.650000,10.10,13.317307,55.147919,47.181816,18.469482,15.072921,14.819800
20180105,20.900000,10.20,13.413461,55.446552,47.454544,18.563713,15.162641,14.858193
20180108,21.500000,10.35,13.509615,55.446552,47.727272,18.705063,15.521520,15.050160
...,...,...,...,...,...,...,...,...
20211224,25.850000,16.85,25.000000,61.099998,75.199997,24.200001,25.049999,27.950001
20211227,25.799999,16.90,25.000000,61.299999,75.199997,24.250000,25.000000,27.950001
20211228,25.950001,17.10,25.049999,62.299999,75.900002,24.350000,25.350000,28.000000
20211229,26.100000,17.60,25.299999,63.000000,76.599998,24.549999,25.500000,28.049999
20211230,25.950001,17.50,25.299999,62.500000,76.300003,24.500000,25.450001,28.049999

In [23]:
start_year = stock_period[0].split('/')[0]
end_year = stock_period[1].split('/')[0]

data = pd.read_csv(f'data/{name}.csv',index_col=0)
train = data.loc['20180101':'20201231']
train.to_csv(f'data/{name}_2018_2020.csv')
test = data.loc['20210101':'20211231']
test.to_csv(f'data/{name}_2021.csv')
test

,2891,2883,2885,2882,2881,2892,5880,2884
DateTime,,,,,,,,
20210104,19.549999,9.24,20.450001,42.049999,42.045452,20.891088,19.754902,23.890032
20210105,19.600000,9.24,20.549999,42.099998,42.136364,21.039602,19.901960,23.842911
20210106,19.549999,9.28,20.650000,41.549999,41.454544,20.792080,19.754902,23.748671
20210107,19.799999,9.29,21.000000,41.900002,42.000000,21.039602,19.754902,23.748671
20210108,20.000000,9.41,21.350000,42.849998,43.136364,21.287128,19.950979,24.031393
...,...,...,...,...,...,...,...,...
20211224,25.850000,16.85,25.000000,61.099998,75.199997,24.200001,25.049999,27.950001
20211227,25.799999,16.90,25.000000,61.299999,75.199997,24.250000,25.000000,27.950001
20211228,25.950001,17.10,25.049999,62.299999,75.900002,24.350000,25.350000,28.000000
20211229,26.100000,17.60,25.299999,63.000000,76.599998,24.549999,25.500000,28.049999
20211230,25.950001,17.50,25.299999,62.500000,76.300003,24.500000,25.450001,28.049999

In [24]:
url = "https://api.finmindtrade.com/api/v4/data"
parameter = {"dataset": "TaiwanStockInfo"}
translation = requests.get(url, params=parameter)
trans = translation.json()
df_info = pd.DataFrame(trans['data'])
drop_list = ['ETF', '上櫃指數股票型基金(ETF)','受益證券', '指數投資證券(ETN)', '其他', '所有證券 ', '存託憑證','Index', '大盤']
df_info = df_info[df_info['industry_category'].apply(lambda x : x not in drop_list)]
df_info['row'] = df_info.sort_values(['stock_id','industry_category'], ascending=[True,False]).groupby(['stock_id']).cumcount() + 1
df_info = df_info[df_info['row']==1]
df_info = df_info[['stock_id','stock_name','industry_category']]
df_info = df_info.rename(columns={'stock_id':'code','stock_name':'name','industry_category':'c_name'})
df_info = df_info[df_info['code'].apply(lambda x : x in Portfolio['portfolio'])]
df_info.to_csv(f'data/{name}_table.csv',index=False)
df_info

      code name c_name
1102  2881  富邦金   金融保險
1106  2882  國泰金   金融保險
1109  2883  開發金   金融保險
1112  2884  玉山金   金融保險
1113  2885  元大金   金融保險
1124  2891  中信金   金融保險
1128  2892  第一金   金融保險
2085  5880  合庫金   金融保險